SPV_EXT_shader_image_int64
==========================

Name Strings
------------

SPV_EXT_shader_image_int64

Contact
-------

To report problems with this extension, please open a new issue at:

https://github.com/KhronosGroup/SPIRV-Headers

Contributors
------------

- Tobias Hector, AMD
- Matthaeus Chajdas, AMD
- Graham Wihlidal, Epic Games

Notice
------

Copyright (c) 2019 The Khronos Group Inc. Copyright terms at
http://www.khronos.org/registry/speccopyright.html

Status
------

- Complete

Version
-------

[width="40%",cols="25,25"]
|========================================
| Last Modified Date | 2021-03-17
| Revision           | 2
|========================================

Dependencies
------------

This extension is written against the SPIR-V Specification,
Version 1.5, Revision 1, Unified.

This extension requires SPIR-V 1.0.

Overview
--------

This extension enables the use of atomic, load, and store operations on
images with a 64-bit format.

Extension Name
--------------

To use this extension within a SPIR-V module, the following
*OpExtension* must be present in the module:

----
OpExtension "SPV_EXT_shader_image_int64"
----

Modifications to the SPIR-V Specification, Version 1.5
------------------------------------------------------


3.11 Image Formats
~~~~~~~~~~~~~~~~~~

Modify Section 3.11, "Image Formats", adding these rows to the Image Formats table:

--
[cols="1,10,6",options="header",width = "100%"]
|====
2+^.^| Image Format | Enabling Capabilities
| 40 | *R64ui*      | *Int64ImageEXT*
| 41 | *R64i*       | *Int64ImageEXT*
|====
--


3.31 Capabilities
~~~~~~~~~~~~~~~~~

Modify Section 3.31, "Capability", adding these rows to the Capability table:

--
[options="header"]
|====
2+^| Capability ^| Enabling Capabilities
| 5016 | *Int64ImageEXT* +
Uses atomic, load, or store instructions on images with 64-bit integer types.
If using atomics, *Int64Atomics* must be declared.
| *Int64*
|====
--


Revision History
----------------

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|====
| Rev | Date       | Author         | Changes
| 1   | 2019-10-23 | Tobias Hector  | Initial revision
| 2   | 2021-03-17 | Spencer Fricke | Clarify Int64Atomics interaction
|====
