SPIR-V Extension SPV_AMD_shader_image_load_store_lod
====================================================

Name Strings
------------

SPV_AMD_shader_image_load_store_lod

Contact
-------

See *Issues* list in the Khronos SPIRV-Headers repository:
https://github.com/KhronosGroup/SPIRV-Headers

Contributors
------------

- Dominik Witczak, AMD
- Quentin Lin, AMD
- Rex Xu, AMD


Notice
------

Copyright (c) 2017 The Khronos Group Inc. Copyright terms at
http://www.khronos.org/registry/speccopyright.html

Status
------

Shipping.

Version
-------

Modified Date: 08/21/2017

Revision:      1

Dependencies
------------

This extension is written against Revision 1 of the version 1.10 of the
SPIR-V Specification.

The extension is written against Revision 1 of the OpenGL extension
AMD_shader_image_load_store_lod.

Overview
--------

This extension is written to provide the functionality of the
AMD_shader_image_load_store_lod, OpenGL Shading Language Specification extension,
for SPIR-V.

This extension enhances *Lod* image operand to also support *OpImageRead*, *OpImageWrite*
and *OpImageSparseRead* image instructions.


Extension Name
--------------

To enable SPV_AMD_shader_image_load_store_lod extension in SPIR-V, use

  OpExtension "SPV_AMD_shader_image_load_store_lod"

Summary
-------

This extension:

- adds a new *CapabilityImageReadWriteLodAMD* capability.
- expands definition of *Lod* image operand, as described in the overview.


Token Number Assignments
------------------------
|==============================
|*CapabilityImageReadWriteLodAMD*|5015
|==============================


Modifications to the SPIR-V Specification, Version 1.10
-------------------------------------------------------

Modify Section 3.31, Capability

Append the following Capability to the table:

[options="header"]
|========================================
|Capability|Depends On|Enabled by Extension
|*CapabilityImageReadWriteLodAMD*
 
Expands *Lod* image operand definition to support image read/write/sparse read operations.|*CapabilityShader*|SPV_AMD_shader_image_load_store_lod
|========================================


Modify Section 3.14, Image Operands

Lod
~~~

(Replace the following sentence:) +
 +
Only valid with explicit-lod instructions. +
 +
(with:) +
 +
Only valid with explicit-lod instructions, *OpImageRead*, *OpImageWrite*, or *OpImageSparseRead*. +


Validation Rules
----------------

None.

Issues
------

None

Revision History
----------------

[cols="5%,10%,15%,70%"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1|08/21/2017|Dominik Witczak|Initial revision based on AMD_shader_image_load_store_lod.
|========================================
