SPV_ALTERA_runtime_aligned
==========================

== Name Strings

SPV_ALTERA_runtime_aligned

== Contact

To report problems with this extension, please open a new issue at:

https://github.com/KhronosGroup/SPIRV-Registry

== Contributors

- Joe Garvey, Intel

== Notice

Copyright (c) 2021 Intel Corporation.  All rights reserved.

== Status

Final draft

== Version

[width="40%",cols="25,25"]
|========================================
| Last Modified Date | 2021-06-29
| Revision           | 1
|========================================

== Dependencies

This extension is written against the SPIR-V Specification,
Version 1.5 Revision 5.

This extension requires SPIR-V 1.0.

== Overview

This extension introduces a new function parameter attribute that can be applied to pointers to indicate that the pointer was allocated with an implementation-specific alignment.   

== Extension Name
To use this extension within a SPIR-V module, the following *OpExtension* must be present in the module:

----
OpExtension "SPV_ALTERA_runtime_aligned"
----

== New capabilities
This extension introduces a new capability:

----
RuntimeAlignedAttributeALTERA
----

== Token Number Assignments

[width="40%"]
[cols="70%,30%"]
[grid="rows"]
|====
| RuntimeAlignedAttributeALTERA  | 5939
| RuntimeAlignedALTERA | 5940 
|====

== Modifications to the SPIR-V Specification, Version 1.5 Revision 5

=== Function Parameter Attribute

Modify Section 3.19, Function Parameter Attribute, adding a row to the table:

--
[options="header"]
|===
2+^| Function Parameter Attribute | Enabling Capabilities
| 5940 | *RuntimeAlignedALTERA* +
Indicates that the pointer comes directly from a runtime allocation and was not offset in any way.  This pointer can thus be assumed to have the implementation-defined alignment with which the corresponding runtime is known to allocate pointers. Only valid for pointer parameters. Not valid on return values. | *RuntimeAlignedAttributeALTERA*
|===
--

=== Capability

Modify Section 3.31, Capability, adding a row to the Capability table:
--
[options="header"]
|====
2+^| Capability ^| Implicitly Declares
| 5939 | *RuntimeAlignedAttributeALTERA* | *Kernel*
|====
--

=== Validation Rules

None.

== Issues

None.

//. Issue.
//+
//--
//*RESOLVED*: Resolution.
//--

== Revision History

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1|2021-06-29|Joe Garvey|*Initial public release*
|======================================== 



