= SPV_ALTERA_global_variable_fpga_decorations
:source-highlighter: coderay
:coderay-linenums-mode: table

// This section needs to be after the document title.
:doctype: book
:toc2:
:toc: left
:encoding: utf-8
:lang: en

== Name Strings

SPV_ALTERA_global_variable_fpga_decorations

== Contact

To report problems with this extension, please open a new issue at:

https://github.com/KhronosGroup/SPIRV-Registry

== Contributors

- Artem Radzikhovskyy, Intel
- Michael Kinsner, Intel
- Joe Garvey, Intel
- Mohammad Fawaz, Intel
- Gregory Lueck, Intel

== Notice

Copyright (c) 2021-2023 Intel Corporation. All rights reserved.

== Status

* Complete

== Version

[width="40%",cols="25,25"]
|========================================
| Last Modified Date | 2023-10-27
| Revision      | 3
|========================================

== Dependencies

This extension is written against the SPIR-V Specification,
Version 1.6 Revision 2.

This extension requires SPIR-V 1.0.

== Overview

This extension adds decorations that can be applied to global (module scope)
variables. These decorations are intended to help code generation for
FPGA devices, they can be ignored by all other consumers of this extension.

== Extension Name
To use this extension within a SPIR-V module, the following *OpExtension* must
be present in the module:

----
OpExtension "SPV_ALTERA_global_variable_fpga_decorations"
----

== New Capabilities
This extension introduces a new capability:

----
GlobalVariableFPGADecorationsALTERA
----

== Token Number Assignments

--
[width="40%"]
[cols="70%,30%"]
[grid="rows"]
|====
|GlobalVariableFPGADecorationsALTERA | 6189
|InitModeALTERA | 6190
|ImplementInRegisterMapALTERA | 6191
|====
--

== Modifications to the SPIR-V Specification, Version 1.6

=== Initialization Mode Qualifier

After Section 3.18, add a new section "3.18a Initialization Mode Qualifier" as follows

Defines how the initialization should be triggered.

Used by InitModeALTERA.

--
[options="header"]
|====
2+^| Initialization Mode Qualifier ^| Enabling Capabilities
// --- ROW BREAK ---
| 0
| *InitOnDeviceReprogramALTERA*

Initialization is performed by reprogramming
 the device. This may require more frequent reprogramming but may reduce
 area.

| *GlobalVariableFPGADecorationsALTERA*

// --- ROW BREAK ---
| 1
| *InitOnDeviceResetALTERA*

Initialization is performed by sending a reset
 signal to the device. This may increase area but may reduce reprogramming
 frequency.
| *GlobalVariableFPGADecorationsALTERA*

|====
--

=== Decoration

Modify Section 3.20, Decoration, adding these rows to the Decoration table:

--
[cols="^4,20,2*5,22",options="header"]
|====
2+^.^| Decoration 2+<.^| Extra Operands | Enabling Capabilities

// --- ROW BREAK ---
| 6190
a|
*InitModeALTERA* +
Only valid on global (module scope) *OpVariable* which has an _Initializer_
operand.

This decoration only has an effect when the consumer is an FPGA or similar
device. The _Trigger_ value tells how the global variable should be
initialized.

If a global *OpVariable* with an _Initializer_ operand is not decorated with
*InitModeALTERA*, the method by which the variable's value is initialized is
implementation defined.

2+| Initialization Mode Qualifier +
_Trigger_
| *GlobalVariableFPGADecorationsALTERA*

// --- ROW BREAK ---
| 6191
a|
*ImplementInRegisterMapALTERA* +
Only valid on global (module scope) *OpVariable*.

This decoration only has an effect when the consumer is an FPGA or similar
device. The _Value_ value controls the interface of this global variable with
hardware outside the boundary of the SPIR-V module.

Legal values of _Value_:

* 0 [False] - Access to this memory is through a dedicated interface.
* 1 [True] - Access to this memory is through a common register map interface that may be shared by other control or data inputs and outputs.

If a global *OpVariable* is not decorated with *ImplementInRegisterMapALTERA*, the
interface for the variable is implementation defined.

2+| Literal Number +
_Value_
| *GlobalVariableFPGADecorationsALTERA*

|====
--

=== Capability

Modify Section 3.31, Capability, adding a row to the Capability table:
--
[options="header"]
|====
2+^| Capability ^| Implicitly Declares
| 6189
|  GlobalVariableFPGADecorationsALTERA
|
|====
--

== Issues

None.

== Revision History

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1|2022-11-1|Gregory Lueck|Initial revision
|2|2023-04-25|Artem Radzikhovskyy| Seperated the FPGA specific decorations from the generic ones 
|3|2023-10-27|Artem Radzikhovskyy|Reverting Capability ID
|========================================
