:extension_name: SPV_INTEL_split_barrier
:capability_name: SplitBarrierINTEL
:capability_token: 6141
:arrive_token: 6142
:wait_token: 6143
:arrive_name: OpControlBarrierArriveINTEL
:wait_name: OpControlBarrierWaitINTEL

{extension_name}
================

== Name Strings

{extension_name}

== Contact

To report problems with this extension, please open a new issue at:

https://github.com/KhronosGroup/SPIRV-Registry

== Contributors

- Ben Ashbaugh, Intel

== Notice

Copyright (c) 2022 Intel Corporation.  All rights reserved.

== Status

- Working Draft

== Version

[width="40%",cols="25,25"]
|========================================
| Last Modified Date | {docdate}
| Revision           | 1
|========================================

== Dependencies

This extension is written against the SPIR-V Specification,
Version 1.6 Revision 1.

This extension requires SPIR-V 1.0.

== Overview

This extension adds SPIR-V instructions to split a control barrier (*OpControlBarrier*) into two separate operations:
the first indicates that an invocation has "arrived" at the barrier but should continue executing,
and the second indicates that an invocation should "wait" for other invocations to arrive at the barrier before executing further.

Splitting a barrier operation may improve performance and may provide a closer match to "latch" or "barrier" operations in other parallel languages such as C++ 20.

== Extension Name

To use this extension within a SPIR-V module, the appropriate *OpExtension* must
be present in the module:

[subs="attributes"]
----
OpExtension "{extension_name}"
----

== New Capabilities

This extension introduces the new capability:

[subs="attributes"]
----
{capability_name}
----

== Modifications to the SPIR-V Specification, Version 1.6

Modify Section 3.31, Capability, adding rows to the Capability table:

--
[options="header"]
|====
2+^| Capability ^| Implicitly Declares 
| {capability_token} | *{capability_name}*
|
|====
--

Add to Section 3.42.20, Barrier Instructions:

[cols="1,1,3*3",width="100%"]
|=====
4+|[[OpControlBarrierArriveINTEL]]*OpControlBarrierArriveINTEL* +
 +
Indicates that an invocation has arrived at a split control barrier.
This may allow other invocations waiting on the split control barrier to continue executing. +
 +
When _Execution_ is *Workgroup* or larger, behavior is undefined unless all invocations within _Execution_ execute the same dynamic instance of this instruction. When _Execution_ is *Subgroup* or *Invocation*, the behavior of this instruction in non-uniform control flow is defined by the client API. +
// TODO: undefined to arrive twice?
 +
If _Semantics_ is not *None*, this instruction also serves as the start of a memory barrier similar to an *OpMemoryBarrier* instruction with the same _Memory_ and _Semantics_ operands.
This allows atomically specifying both a control barrier and a memory barrier (that is, without needing two instructions). If _Semantics_ is *None*, _Memory_ is ignored. +
1+|Capability: +
*{capability_name}*
1+| 4 | {arrive_token}
| 'Scope <id>' +
'Execution'
| 'Scope <id>' +
'Memory'
| 'Scope Memory Semantics <id>' +
'Semantics'
|=====

[cols="1,1,3*3",width="100%"]
|=====
4+|[[OpControlBarrierWaitINTEL]]*OpControlBarrierWaitINTEL* +
 +
Waits for other invocations of this module to arrive at a split control barrier. +
 +
When _Execution_ is *Workgroup* or larger, behavior is undefined unless all invocations within _Execution_ execute the same dynamic instance of this instruction. When _Execution_ is *Subgroup* or *Invocation*, the behavior of this instruction in non-uniform control flow is defined by the client API. +
// TODO: undefined to wait twice?
 +
If _Semantics_ is not *None*, this instruction also serves as the end of a memory barrier similar to an *OpMemoryBarrier* instruction with the same _Memory_ and _Semantics_ operands.
This ensures that memory accesses issued before arriving at the split barrier are observed before memory accesses issued after this instruction.
This control is ensured only for memory accesses issued by this invocation and observed by another invocation executing within _Memory_ scope.
This allows atomically specifying both a control barrier and a memory barrier (that is, without needing two instructions). If _Semantics_ is *None*, _Memory_ is ignored. +
1+|Capability: +
*{capability_name}*
1+| 4 | {wait_token}
| 'Scope <id>' +
'Execution'
| 'Scope <id>' +
'Memory'
| 'Scope Memory Semantics <id>' +
'Semantics'
|=====

== Issues

// . first issue
// +
// --
// *RESOLVED*:
// --
None.

== Revision History

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1|2022-02-24|Ben Ashbaugh|Initial revision
|========================================
