:extension_name: SPV_INTEL_memory_access_aliasing

:capability_name: MemoryAccessAliasingINTEL
:capability_token: 5910
:OpAliasDomainDeclINTEL_token: 5911
:OpAliasScopeDeclINTEL_token: 5912
:OpAliasScopeListDeclINTEL_token: 5913
:AliasScopeINTEL_token: 5914
:NoAliasINTEL_token: 5915

= {extension_name}

== Name Strings

{extension_name}

== Contact

To report problems with this extension, please open a new issue at:

https://github.com/KhronosGroup/SPIRV-Registry

== Contributors

- Dmitry Sidorov, Intel +
- Alexey Sotkin, Intel +
- Qi Ye, Intel +

== Notice

Copyright (c) 2026 Intel Corporation. All rights reserved.

== Status

* Shipping

== Version

[width="40%",cols="25,25"]
|========================================
| Last Modified Date | 2026-08-05
| Revision           | 3
|========================================

== Dependencies

This extension is written against the SPIR-V Specification, Version 1.6
Revision 7.

This extension requires SPIR-V 1.0.

== Overview

This extension adds *AliasDomainDeclINTEL*, *AliasScopeINTEL* and
*AliasScopeListDeclINTEL* instructions that serve a purpose to
specify aliasing scopes within which annotated memory accesses don't alias.
Also the extension adds *AliasScopeINTEL* and *NoAliasINTEL* decorations and _Memory Operands_ mask
to annotate memory access instructions. The decorations and _Memory Operands_ value
use result IDs of the new instructions to specify noalias memory-access set.

When evaluating an aliasing query if two memory access instructions that
have *AliasScopeINTEL* or *NoAliasINTEL* memory operands or decorated
with *AliasScopeINTEL* or *NoAliasINTEL* decorations and if for some domain,
the set of scopes with that domain in one instruction's aliasing scope list is
a subset of (or equal to) the set of scopes for that domain in another
instruction's noalias list, then the two memory accesses are assumed not to alias.
If this assumption is violated in runtime - the behaviour is undefined.

The extension helps generating more efficient code (for example helps auto-vectorization) and
doesn't affect semantics of the user's program.

This functionality is equal to LLVM's _alias.scope_ and _noalias_ metadata, see:
https://llvm.org/docs/LangRef.html#noalias-and-alias-scope-metadata .

== Extension Name

To use this extension within a SPIR-V module, the following *OpExtension* must
be present in the module:

[subs="attributes"]
----
OpExtension "{extension_name}"
----

== Modifications to the SPIR-V Specification, Version 1.6

=== Modifications 2.4 Logical Layout of a Module

Insert an extra item before "8. All annotation instructions"

[start=8]
. Optional *OpAliasDomainDeclINTEL*, *OpAliasScopeDeclINTEL* and *OpAliasScopeDeclINTEL*
instructions.


=== Capabilities

Modify Section 3.2.30, "Capability", adding these rows to the Capability table:

--
[cols="^.^2,16,15",options="header",width = "100%"]
|====
2+^| Capability ^| Depends On
| {capability_token} | *{capability_name}* +
Allow to use *OpAliasDomainDeclINTEL*, *OpAliasScopeDeclINTEL* and
*OpAliasScopeListDeclINTEL* instructions, *AliasScopeINTEL* and *NoAliasINTEL* decorations
and *AliasScopeINTEL* and *NoAliasINTEL* _Memory Operands_. |
|====
--

=== Instructions

[cols="4", width="100%"]
|=====
3+|*OpAliasDomainDeclINTEL* +
The instruction declares an aliasing domain.

The _Result_ is used by *OpAliasScopeDeclINTEL* instruction to form aliasing
scope.

Optional <id> _Name_ parameter is used to specify an unique domain in global
scope.
| Capability:
*{capability_name}*

| 3 | {OpAliasDomainDeclINTEL_token} | <id> _Result_ | optional <id> _Name_
|=====

[cols="5", width="100%"]
|=====
4+|*OpAliasScopeDeclINTEL* +
The instruction declares an aliasing scope.

The _Result_ is used by *OpAliasScopeListDeclINTEL* instruction to form aliasing
scope list.

<id> _AliasDomain_ parameter specifies aliasing domain within this aliasing
scope, it must be the result id of *OpAliasDomainDeclINTEL* instruction.

Optional <id> _Name_ parameter is used to specify an unique domain in
global scope.
| Capability:
*{capability_name}*

| 4 | {OpAliasScopeDeclINTEL_token} | <id> _Result_ | <id> _AliasDomain_ | optional <id> _Name_
|=====

[cols="4", width="100%"]
|=====
3+|*OpAliasScopeListDeclINTEL* +
The instruction declares a list of aliasing scopes.

The _Result_ is used by _AliasScopeINTEL_ and _NoAliasINTEL_ decorations and
_AliasScopeINTEL_ and _NoAliasINTEL_ memory operands.

<id> _AliasScope1_, ... , <id> _AliasScopeN_ parameters specifies aliasing
scopes that form aliasing list of scopes, it must be the result id of *OpAliasScopeDeclINTEL*.
| Capability:
*{capability_name}*

| 3+ | {OpAliasScopeListDeclINTEL_token} | <id> _Result_ | <id> _AliasScope1_, <id> _AliasScope2_, ... , <id> _AliasScopeN_
|=====

=== Decorations

Modify Section 3.2.19 "Decoration", adding these rows to Decoration table:

--
[options="header"]
|====
2+^| Decoration 2+^| Extra Operands ^| Enabling Capabilities
| {AliasScopeINTEL_token} | *AliasScopeINTEL* +
Can only be applied to _OpFunctionCall_ and _Atomic_ instruction. Has
_Aliasing Scopes List_ <id> operand pointing to a result of
*OpAliasScopeListDeclINTEL* instruction, that specifies a set of aliasing scopes
in which memory access instruction is assumed to be not aliased with any other
memory instructions with intersecting aliasing scopes in case if these
accesses are decorated with _NoAliasINTEL_ decoration or have _NoAliasINTEL_
memory operand.
2+| <id> _Aliasing Scopes List_ | *{capability_name}*
| {NoAliasINTEL_token} | *NoAliasINTEL* +
Can only be applied to _OpFunctionCall_ and _Atomic_ instructions. Has
_Aliasing Scopes List_ <id> operand pointing on a result of
*OpAliasScopeListDeclINTEL* instruction, that specifies a set of aliasing scopes
in which memory access instruction is assumed to be not aliased with any other
memory instructions with intersecting aliasing scopes in case if these
accesses are decorated with _AliasScopeINTEL_ decoration or have
_AliasScopeINTEL_ memory operand.
2+| <id> _Aliasing Scopes List_ | *{capability_name}*
|====
--

=== Memory Operands

Modify Section 3.26 "Memory Operands", adding these rows to Memory Operands
table:

--
[options="header"]
|====
2+^| Memory Operands | Extra Operands | Enabling Capabilities
| 0x10000 | *AliasScopeINTEL* +
Defines aliasing rules for memory access in the current aliasing scope.
Assume that the memory access doesn't alias with any other memory accesses with
aliasing scopes in _Aliasing Scopes List_ intersecting with the current one in
case if these accesses have _NoAliasINTEL_ memory operand or are
decorated with _NoAliasINTEL_ decoration.
| <id> _Aliasing Scopes List_ |
*{capability_name}*
| 0x20000 | *NoAliasINTEL* +
Defines aliasing rules for memory access in the current aliasing scope.
Assume that the memory access doesn't alias with any other memory accesses with
aliasing scopes in _Aliasing Scopes List_ intersecting with the current one in
case if these accesses have _AliasScopeINTEL_ memory operand or are
decorated with _AliasScopeINTEL_ decoration.
| <id> _Aliasing Scopes List_ |
*{capability_name}*
|====
--

== Issues


== Revision History

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1|2021-02-15|Dmitry Sidorov|Initial revision
|2|2022-01-24|Dmitry Sidorov|Remove mutually exclusive restriction
|3|2026-08-05|Qi Ye|Prepare for publication
|========================================
