SPV_INTEL_fpga_cluster_attributes
=================================

== Name Strings

SPV_INTEL_fpga_cluster_attributes

== Contact

To report problems with this extension, please open a new issue at:

https://github.com/KhronosGroup/SPIRV-Registry

== Contributors

- Jessica Davies, Intel

== Notice

Copyright (c) 2020 Intel Corporation.  All rights reserved.

== Status

Final draft

== Version

[width="40%",cols="25,25"]
|========================================
| Last Modified Date | 2020-10-13
| Revision           | A
|========================================

== Dependencies

This extension is written against the SPIR-V Specification,
Version 1.5 Revision 3.

This extension requires SPIR-V 1.0.

== Overview

This extension adds a decoration to request that statically-scheduled clusters use a stall-enable signal, on an FPGA target.

== Extension Name

To use this extension within a SPIR-V module, the following *OpExtension* must be present in the module:

----
OpExtension "SPV_INTEL_fpga_cluster_attributes"
----

== New capabilities
This extension introduces a new capability:

----
FPGAClusterAttributesINTEL
----

== New Decorations

This extension adds the following decoration under the *FPGAClusterAttributesINTEL* capability:

----
StallEnableINTEL
----

== Token Number Assignments

--
[width="40%"]
[cols="70%,30%"]
[grid="rows"]
|====
|FPGAClusterAttributesINTEL|5904
|StallEnableINTEL          |5905
|====
--

== Modifications to the SPIR-V Specification, Version 1.5

=== Decoration

Modify Section 3.20, Decoration, adding these rows to the Decoration table:

--
[options="header"]
|====
2+^| Decoration 2+^| Extra Operands ^| Enabling Capabilities
| 5905 | *StallEnableINTEL* +
Only valid on OpFunction. Request, to the extent possible, that statically-scheduled clusters should handle stalls using a stall-enable signal to freeze computation within the cluster.
2+| | *FPGAClusterAttributesINTEL*
|====
--

=== Capability

Modify Section 3.31, Capability, adding a row to the Capability table:
--
[options="header"]
|====
2+^| Capability ^| Implicitly Declares
| 5904 | FPGAClusterAttributesINTEL |
|====
--

=== Validation Rules

None.

== Issues

None.

== Revision History

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1|2020-10-13|Jessica Davies|*Initial public release*
|========================================
