SPV_INTEL_fpga_memory_attributes
================================

== Name Strings

SPV_INTEL_fpga_memory_attributes

== Contact

To report problems with this extension, please open a new issue at:

https://github.com/KhronosGroup/SPIRV-Headers

== Contributors

- Ben Ashbaugh, Intel +
- Joe Garvey, Intel +
- Michael Kinsner, Intel

== Notice

Copyright (c) 2019 Intel Corporation.  All rights reserved.

== Status

Final draft

== Version

[width="40%",cols="25,25"]
|========================================
| Last Modified Date | {docdate}
| Revision           | C
|========================================

== Dependencies

This extension is written against the SPIR-V Specification,
Version 1.3 Revision 6.

This extension requires SPIR-V 1.0.

== Overview

This extension adds decorations that influence compiler generation of memory structures on an FPGA target.

== Extension Name
To use this extension within a SPIR-V module, the following *OpExtension* must be present in the module:

----
OpExtension "SPV_INTEL_fpga_memory_attributes"
----
 
== New capabilities
This extension introduces a new capability:

----
FPGAMemoryAttributesINTEL
----

== New Decorations

Decorations added under the *FPGAMemoryAttributes* capability:

----
RegisterINTEL
MemoryINTEL
NumbanksINTEL
BankwidthINTEL
MaxconcurrencyINTEL
SinglepumpINTEL
DoublepumpINTEL
----

== Token Number Assignments

--
[width="40%"]
[cols="70%,30%"]
[grid="rows"]
|====
|FPGAMemoryAttributesINTEL|5824
|RegisterINTEL            |5825
|MemoryINTEL              |5826
|NumbanksINTEL            |5827
|BankwidthINTEL           |5828
|MaxconcurrencyINTEL      |5829
|SinglepumpINTEL          |5830
|DoublepumpINTEL          |5831
|==== 
--

== Modifications to the SPIR-V Specification, Version 1.3

=== Decoration

Modify Section 3.20, Decoration, adding these rows to the Decoration table:

--
[options="header"]
|====
2+^| Decoration	^| Enabling Capabilities ^| Extra Operands
| 5825 | *RegisterINTEL* +
Apply to a variable or a structure-type member. Request, to the extent possible, that the variable or structure member should be implemented in logic and carried through the datapath. 
| *FPGAMemoryAttributesINTEL* |
| 5826 | *MemoryINTEL* +
Apply to a variable or a structure-type member. Request, to the extent possible, that the variable or structure member should be implemented in memory of the specified type. 
| *FPGAMemoryAttributesINTEL* | Literal String +
_Memory Type_
| 5827 | *NumbanksINTEL*  +
Apply to a variable or a structure-type member. Request, to the extent possible, that the variable or structure member should be implemented in a memory with the specified number of banks.
| *FPGAMemoryAttributesINTEL* | Literal Number +
_Banks_
| 5828 | *BankwidthINTEL* +
Apply to a variable or a structure-type member. Request, to the extent possible, that the variable or structure member should be implemented in a memory whose banks have the specified width in bytes.
| *FPGAMemoryAttributesINTEL* | Literal Number +
_Bank Width_
| 5829 | *MaxconcurrencyINTEL* +
Apply to a variable or a structure-type member. Request, to the extent possible, that the implementation allow no more than the specified number of threads or loop iterations to access the variable or structure-type member concurrently.  
| *FPGAMemoryAttributesINTEL* | Literal Number +
_Maximum Concurrency_
| 5830 | *SinglepumpINTEL* +
Apply to a variable or a structure-type member. Request, to the extent possible, that the variable or structure member should be implemented in a memory that is clocked at the same rate as accesses to it.
| *FPGAMemoryAttributesINTEL* |
| 5831 | *DoublepumpINTEL* +
Apply to a variable or a structure-type member. Request, to the extent possible, that the variable or structure member should be implemented in a memory that is clocked at twice the rate of accesses to it.
| *FPGAMemoryAttributesINTEL* |
|====
--

=== Capability

Modify Section 3.31, Capability, adding a row to the Capability table:
--
[options="header"]
|====
2+^| Capability ^| Implicitly Declares
| 5824 | FPGAMemoryAttributesINTEL | Reserved. +

Also see extension: + 
*SPV_INTEL_fpga_memory_attributes*
|====
--

=== Validation Rules

None.

== Issues

None.

//. Issue.
//+
//--
//*RESOLVED*: Resolution.
//--

== Revision History

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|A|2019-02-27|Joe Garvey|*Initial public release*
|B|2019-03-18|Joe Garvey|Added MaxconcurrencyINTEL decoration.  Fixed NumbanksINTEL capitalization
|C|2019-04-23|Joe Garvey|Added SinglepumpINTEL and DoublepumpINTEL decorations
|======================================== 
