SPV_KHR_bit_instructions
========================

Name Strings
------------

SPV_KHR_bit_instructions

Contact
-------

To report problems with this extension, please open a new issue at:

https://github.com/KhronosGroup/SPIRV-Headers

Contributors
------------

- Ben Ashbaugh, Intel

Status
------

- Complete
- Approved by the SPIR Working Group: 2021-03-10
- Approved by the Khronos Board of Promoters: 2021-04-23

Version
-------

[width="40%",cols="25,25"]
|========================================
| Last Modified Date | 2021-06-23
| Revision           | 1
|========================================

Dependencies
------------

This extension is written against the SPIR-V Specification, Version 1.5 Revision 5.

This extension requires SPIR-V 1.0.

Overview
--------

This enables the following bit instructions to be used by SPIR-V modules without requiring the *Shader* capability:

* *OpBitFieldInsert*
* *OpBitFieldSExtract*
* *OpBitFieldUExtract*
* *OpBitReverse*

Extension Name
--------------

To use this extension within a SPIR-V module, the following
*OpExtension* must be present in the module:

----
OpExtension "SPV_KHR_bit_instructions"
----

New Capabilities
----------------

This extension introduces the new capability:

----
BitInstructions
----


Modifications to the SPIR-V Specification, Version 1.5
------------------------------------------------------

Modify Section 3.31, "Capability", adding this row to the Capability table:

--
[cols="1^.^,15,15",options="header"]
|====
2+^| Capability ^| Implicitly Declares
| 6025 | *BitInstructions* +
Uses the bit reverse, bitfield insert, and bitfield extract instructions. |
|====
--

Modify Section 3.37.14, "Bit Instructions", adding the *BitInstructions* capability to the following instructions:

[cols="1,1,6*3",width="100%"]
|=====
5+|[[OpBitFieldInsert]]*OpBitFieldInsert* +
 +
(The description of this instruction is unchanged.)
3+|<<Capability,Capability>>: +
*Shader* +
*BitInstructions*
| 7 | 201
 | '<id>' +
'Result Type' | <<ResultId,'Result <id>' >> | '<id>' +
'Base' | '<id>' +
'Insert' | '<id>' +
'Offset' | '<id>' +
'Count'

|=====

[cols="1,1,5*3",width="100%"]
|=====
5+|[[OpBitFieldSExtract]]*OpBitFieldSExtract* +
 +
(The description of this instruction is unchanged.)
2+|<<Capability,Capability>>: +
*Shader* +
*BitInstructions*
| 6 | 202
 | '<id>' +
'Result Type' | <<ResultId,'Result <id>' >> | '<id>' +
'Base' | '<id>' +
'Offset' | '<id>' +
'Count'
|=====

[cols="1,1,5*3",width="100%"]
|=====
5+|[[OpBitFieldUExtract]]*OpBitFieldUExtract* +
 +
(The description of this instruction is unchanged.)
2+|<<Capability,Capability>>: +
*Shader* +
*BitInstructions*
| 6 | 203
 | '<id>' +
'Result Type' | <<ResultId,'Result <id>' >> | '<id>' +
'Base' | '<id>' +
'Offset' | '<id>' +
'Count'
|=====

[cols="1,1,3*3",width="100%"]
|=====
3+|[[OpBitReverse]]*OpBitReverse* +
 +
(The description of this instruction is unchanged.)
2+|<<Capability,Capability>>: +
*Shader* +
*BitInstructions*
| 4 | 204
 | '<id>' +
'Result Type' | <<ResultId,'Result <id>' >> | '<id>' +
'Base'

|=====

Validation Rules
----------------

No new validation rules are required.

Issues
------

None yet.

Revision History
----------------

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1 |2021-06-23 |Ben Ashbaugh|Internal revisions
|========================================
