SPV_NV_sample_mask_override_coverage
====================================

Name Strings
------------

SPV_NV_sample_mask_override_coverage

Contact
-------

To report problems with this extension, please open a new issue at:

https://github.com/KhronosGroup/SPIRV-Registry

Contributors
------------

- Kerch Holt, NVIDIA
- Daniel Koch, NVIDIA

Status
------

Complete.

Version
-------

[width="40%",cols="25,25"]
|========================================
| Last Modified Date | 2017-02-15
| Revision           | 3
|========================================

Dependencies
------------

This extension is written against the SPIR-V Specification,
Version 1.1 Revision 4.

This extension requires SPIR-V 1.0.

Overview
--------

This extension provides a new builtin variable decoration
to support the OpenGL GL_NV_sample_mask_override_coverage and
Vulkan VK_NV_sample_mask_override_coverage extensions in SPIR-V.

The *OverrideCoverageNV* decoration corresponds to the *override_coverage* layout
qualifier annotation.

Extension Name
--------------

To use this extension within a SPIR-V module, the following
*OpExtension* must be present in the module:

----
OpExtension "SPV_NV_sample_mask_override_coverage"
----

New Capabilities
----------------

This extension introduces a new capability:

----
SampleMaskOverrideCoverageNV
----

that depends on the *SampleRateShading* capability.

New Decorations
---------------

Decorations added under the *SampleMaskOverrideCoverageNV* capability

----
OverrideCoverageNV
----

New Builtins
------------

None.

New Instructions
----------------

None.

Token Number Assignments
------------------------

[width="40%"]
[cols="70%,30%"]
[grid="rows"]
|====
|OverrideCoverageNV           | 5248
|SampleMaskOverrideCoverageNV | 5249
|====


Modifications to the SPIR-V Specification, Version 1.1
------------------------------------------------------
(Modify Section 3.20, Decoration, adding a row to the Decoration table) ::
+
--
[cols="^1,10,^6,2*2",options="header",width = "100%"]
|====
2+^.^| Decoration | <<Capability,Enabling Capabilities>> 2+<.^| Extra Operands
| 5248 | *OverrideCoverageNV* +
Allows the fragment shader to control whether the
SampleMask builtin output can enable samples that were not covered
by the original primitive, or that failed the early depth/stencil tests.
|*SampleMaskOverrideCoverageNV* 2+|
|====
--

(Modify Section 3.31, Capability, adding a row to the Capability table) ::
+
--
[cols="^.^1,10,^8,15",options="header",width = "80%"]
|====
2+^.^| Capability | Implicitly Declares | Enabled by Extension
| 5249 | *SampleMaskOverrideCoverageNV* | *SampleRateShading* | *SPV_NV_sample_mask_override_coverage*
|====
--


Validation Rules
----------------

An OpExtension must be added to the SPIR-V for validation layers to check
legal use of this extension:

----
OpExtension "SPV_NV_sample_mask_override_coverage"
----

Issues
------

None.

Revision History
----------------

[cols="5%,12%,13%,70%"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1|2016-05-25|Kerch Holt|*Initial revision*
|2|2016-11-24|Daniel Koch|Add capability, assign tokens.
   Improve formatting.
|3|2017-02-15|Daniel Koch|Mark complete, mention Vulkan extension
|========================================

